### PR TITLE
Updated _AGESEXV2.py to account for OREC value of "3"

### PR DESCRIPTION
**Pull request by dr00b**
Addressing #31

### CODE REVIEW

**Comment by dr00b** [comment]
@kevinbuchanjr Yubin just started a new job, tight on time.

Pls validate this if you have the time, not sure why I can't assign you as reviewer. If you approve, I'll merge.

**Review by kevinbuchanjr — COMMENTED** [review]
@dr00b This change is fine with me, with the following caveats:

HCCs were developed by CMS to predict costs for beneficiaries in Medicare Advantage.

It is exceedingly rare that the original entitlement reason for a Medicare Advantage beneficiary is "Both DIB and ESRD" (i.e., "3"), although it does happen. I have seen it increase from 0.01% to 0.20% over the past year. For this reason, I have similar code in my local branch. To the best of my knowledge, these beneficiaries must enroll through a special needs plan (i.e., HCCPY model eligibility "SNPNE", or SNP NE; See https://www.medicareadvantage.com/resources/medicare-advantage-for-people-under-65). I am not sure that HCCPY accounts for this--I think that we rely on the user to submit model eligibility and compute accordingly.

That being said, I would guess that users probably calculate HCCs using HCCPY on Fee-For-Service (FFS) data, as well. You will see a lot of FFS original entitlement reason codes of "Both DIB and ESRD," in which case the update that includes "3" is more relevant. Again, I believe the model eligibility must be "SNPNE" or "SNP NE" in this case.

@t-kychen @dr00b @yubin-park If you have any protestations to the caveats mentioned here, let me know. Otherwise, I am happy to approve the commit when I hear back that you agree.

**Comment by dr00b** [comment]
@kevinbuchanjr thanks for this detail. I am seeing similarly small proportions in FFS claims. Working thru contract modeling for an ACO.

**Comment by kevinbuchanjr** [comment]
Great, @dr00b. Thank you for reviewing my comment! I approve the merge.

**Pull request merged**
